excluded:
- SAMPLES
disabled_rules:
- identifier_name
- type_body_length
- function_body_length

line_length:
- 200 # warning
- 500 # error

cyclomatic_complexity:
- 15 # warning
- 30 # error

function_body_length:
- 75 # warning
- 100 # error